### ISSUE TITLE
Jump tilt isn't smooth

### ISSUE THREAD

**Issue by ghost** [SmajloSlovakian/Minecraft-Jump-Tilt#1]
No matter how fast the speed value is set to, the jump tilt appears choppy and not smooth.

**Comment by SmajloSlovakian** [comment]
ohh sorry... that's due to my dumbness... the value is being reset everytime the config gets reloaded because i made a mistake... will fix it today

**Comment by SmajloSlovakian** [comment]
fixed in 1.2.0... i also fixed some other bugs and that led to smoothing out the default speed...
