### ISSUE TITLE
Low Framerate makes jumptilt freak out (V1.2.0)

### ISSUE THREAD

**Issue by NolanHewitt** [SmajloSlovakian/Minecraft-Jump-Tilt#2]
https://github.com/SmajloSlovakian/Minecraft-Jump-Tilt/assets/52480898/59fd3ccb-8c44-4921-8263-832c9bc906de

Seems to only happen at very low frame rates, below 20fps.

**Comment by SmajloSlovakian** [comment]
okay... i changed my approach to smoothing out the tilting again... i hope no more issues come with this update 🥴

fixed in 1.3.0
